.ci/pipeline_definitions
.ci/run-golang-check
bindings-go/Makefile
bindings-go/go.mod
bindings-go/go.sum
bindings-go/hack/check.sh
bindings-go/hack/install-requirements.sh

Configures a pipline that runs linter, formatter and unittest execution for the go bindings.
@ccwienk I added an additional pipeline step to be able to use the golang image. 
Alternatively, I could add a `golang_unittest` function to `.ci/run-unittest` which mean that I would then need to install go first. 
```improvement operator
NONE
```

configure unittests and linter for go bindings

---

.ci/pipeline_definitions
bindings-go/apis/v2/componentdescriptor.go
bindings-go/apis/v2/constants.go
bindings-go/apis/v2/default.go
bindings-go/apis/v2/validation/validation.go
bindings-go/apis/v2/validation/validation_test.go

Adds labels and the component name to the go binding of the component descriptor.
Also added the oci media type and component descriptor filename as constants.
/invite @Diaphteiros 
```improvement operator
NONE
```

Add labels and component name to go binding

---

bindings-go/apis/v2/accesstypes.go
bindings-go/apis/v2/codecs.go
bindings-go/apis/v2/resources.go
bindings-go/codec/codec_suite_test.go

The go test now also uses the shared example.
Added github as possible access type.
Currently the test still fails because of a required version in the sources:
```
should decode a simple component [It]
/Users/d064999/go/src/github.com/gardener/component-spec/bindings-go/codec/codec_suite_test.go:35
Unexpected error:
<errors.aggregate | len:1, cap:1>: [
{
Type: "FieldValueRequired",
Field: "component.sources[0].version",
BadValue: "",
Detail: "must specify a version",
},
]
component.sources[0].version: Required value: must specify a version
occurred
```
/hold
```improvement operator
NONE
```

Fix test and add github type

---

bindings-go/apis/v2/accesstypes.go
bindings-go/apis/v2/codecs.go
bindings-go/apis/v2/componentdescriptor.go
bindings-go/apis/v2/default.go
bindings-go/apis/v2/validation/validation.go
bindings-go/apis/v2/validation/validation_test.go
bindings-go/codec/codec_suite_test.go
bindings-go/examples/custom/main.go
bindings-go/examples/main.go

Fixes the current go test by now allowing additional attributes for resources and sources.
The validator does now also not enforce a version for a source.
```improvement operator
NONE
```

Fix go bindings and allow additional type attributes

---

.gitignore
bindings-python/gci/oci.py
doc/.gitattributes
doc/Blob.png
doc/Build.png
doc/index.rst
doc/oci.rst

This PR adds a description for the OCI representation of component artefacts and components and the transport format used to upload/download content from a landscape repo.
Fixes #
```improvement operator
```

oci mapping spec

---

component-descriptor-v2-schema.yaml

In some cases, it is a valueable metadata to know which components stem
from which sources. Add an optional src-refs attribute to resources that
allows to express this relationship.
Add an optional `labels` attribute to src-refs, to allow for the
specification of additional metadata (e.g. a subset of actually relevant
sources).

add (optional) src-refs

---

bindings-python/gci/componentmodel.py

Fixes/changes type of default value of ComponentReference's `extraIdentity` field to dict.
PyYaml serializes tuples to yaml-lists, which causes an issue when trying to de-serialize the cd again as dacite detects a type mismatch.

Fix type of default value

---

bindings-go/apis/v2/componentdescriptor.go

Fixes the extra identity attribute getter for component references
```improvement operator
NONE
```

fix extra identity getter for component references

---

bindings-python/gci/__init__.py
bindings-python/gci/componentmodel.py
bindings-python/setup.py

Includes the json-schema-file of the CD in the built package and uses it to parse all generated CDs
I haven't yet come up with a way to properly test our existing component descriptors. I'd hold of merging until we've run them all throug validation at least once 🤔

Validate Parsed Component Descriptor

---

bindings-go/apis/v2/cdutils/cdutils_suite_test.go
bindings-go/apis/v2/cdutils/resource_test.go
bindings-go/apis/v2/cdutils/resources.go
bindings-go/apis/v2/codecs.go
bindings-go/go.mod

added helper functions for image reference access.
Fixes #
cc @danielfoehrKn 
```improvement operator
NONE
```

add helper functions for image references

---

bindings-go/apis/v2/cdutils/resource_test.go
bindings-go/apis/v2/cdutils/resources.go

Adding a simple utility function to get image repo and tag from an image reference.
Fixes #
```improvement operator
```

Add utility function to get image repo and tag from image reference

---

bindings-go/apis/v2/cdutils/resource_test.go
bindings-go/apis/v2/cdutils/resources.go

Renamed to `ParseImageReference` and returns the separator as a third argument.
Fixes #
```improvement operator
```

Rename and fix GetRepositoryAndTagFromReference util function

---

bindings-go/apis/v2/accesstypes.go
bindings-go/apis/v2/cdutils/utils.go
bindings-go/apis/v2/componentdescriptor.go
bindings-go/apis/v2/default.go
bindings-go/apis/v2/helper.go
bindings-go/apis/v2/list.go
bindings-go/ctf/componentarchive.go
bindings-go/ctf/ctf.go
bindings-go/ctf/ctfutils/ctfutils.go
bindings-go/go.mod
bindings-go/go.sum
bindings-go/oci/oci_suite_test.go
bindings-go/oci/resolve.go
bindings-go/oci/resolve_test.go

Improve the repository context handling in the resolver so that the repository context in the descriptor is only treated as information.
We do not rely on that field anymore.
also added:
- a optional cache for the oci resolver
- a util function to traverse all component references
- unit tests for the resolver and the cache
Fixes #
```breaking user
[GO Binding]
The component descriptors `RepositoryContext` is now only for information purposes.
All tooling should not rely on that fields anymore. The provided user repository context should be used instead.
```
```breaking developer
[GO Binding]
The `ctf.ComponentResolver` has been adjusted so that the BlobResolver …
```

Improve the repository context handling in the resolver

---

bindings-python/gci/componentmodel.py

Removes special enum-handling for resource-types `blueprint` and `helm`. These are to be handled as strings, similar to almost all other possible types.
Also lint.

Remove superfluous resource types

---

doc/component_descriptor_registries.rst
language-independent/component-descriptor-v2-schema.yaml

There are, unfortunately, OCI-Registries that do not support arbitrary
image-name-paths (e.g. docker-hub, registry.alicloud). Also, there are
retrictions as to the maximum allowed name-length (currently known for
registry.alicloud).
Add a new attribute specifying how component-names be mapped to
oci-artifacts, with a hash-digest-variant as an alternative to using the
original component-name.
Fixes #
```improvement operator
```

add optional component-name-mapping to repository-ctx

---

bindings-python/tests/gci/componentmodel_test.py
language-independent/component-descriptor-v2-schema.yaml

Python validation will not detect an illegal `None` as version otherwise. 
For a basic reproducer, you can use the following CD:
```yaml
component:
componentReferences: []
labels: []
name: github.com/gardener/aws-lb-readvertiser
provider: internal
repositoryContexts:
- baseUrl: eu.gcr.io/sap-se-gcr-k8s-private/cnudie/gardener/development
type: ociRegistry
resources:
- access:
imageReference: eu.gcr.io/gardener-project/gardener/aws-lb-readvertiser:0.7.0
type: ociRegistry
extraIdentity: {}
labels: []
name: aws-lb-readvertiser
relation: local
srcRefs: []
type: ociImage
version: 0.7.0
sources:
- access:
commit: a66fff3ba92bad9132419266cfbd1c58fd51a7d2
ref: refs/tags/0.7.0
repoUrl: github.com/gardener/aws-lb-readvertiser
type: github
extraIdentity: {}
labels: []
name: aws-lb-readvertiser
type: …
```

Define version-attribute type in referenced config

---

bindings-go/ctf/componentarchive.go

passes through decode options when loading a component archive. feature is needed as we must be able to disable validation when loading invalid components descriptors (e.g. where some fields are not yet set) in the component cli.
Fixes #
```improvement operator
```

passes through component descriptor decode options

---

doc/building_components.rst

Fixes a typo in the docs.
None
```improvement operator
NONE
```

Fix URL typo in 'Building Components' doc

---

bindings-go/apis/v2/cdutils/utils.go
bindings-go/apis/v2/cdutils/utils_test.go

This pull request fixes function `cdutils.MergeIdentityObjectMeta`. Among others, the function merges two slices of Labels, but has the following issues:
- It panics if the second slice of Labels is longer than the first,
- Depending on the order of the labels, it replaces the wrong label.
Fixes #
```improvement operator
NONE
```

Fix merge labels

---

bindings-go/apis/v2/componentdescriptor.go
bindings-go/apis/v2/signatures/normalize.go
bindings-go/apis/v2/signatures/normalize_test.go
bindings-go/apis/v2/signatures/rsa.go
bindings-go/apis/v2/signatures/sign_test.go
bindings-go/apis/v2/signatures/types.go
bindings-go/examples/signatures/main.go

CD normalisation algorithm now contains several more fields such as componentName, relation, res.type. Additionally, a special digest can indicate to exclude a resource from signing.
Fixes #
```improvement user
BREAKING: CD normalisation algorithm now contains more attributes. Already created signatures have to be recreated.
BREAKING: Special Digest annotation can be set to exclude a resource from signing.
BREAKING: renaming some constants
```

Improvement of Signing/Verification

---

doc/proposal/component-descriptor-v2-schema.yaml

This pull request adjusts the proposal json schema for the component descriptor. 
The field definitions concerning digests and signing are taken over from the current [JSON schema for the component descriptor](https://github.com/gardener/component-spec/blob/master/language-independent/component-descriptor-v2-schema.yaml).
Fixes #
```improvement operator
NONE
```

Add signing fields to component descriptor schema

---

bindings-go/apis/v2/signatures/const.go
bindings-go/apis/v2/signatures/rsa.go
bindings-go/apis/v2/signatures/types.go

- makes hash function configurable
- pass in hash function in rsa.Sign() and rsa.Verify() calls instead of passing in 0. this will apply EMSA-PKCS1-v1_5 encoding (https://datatracker.ietf.org/doc/html/rfc3447#section-9.2) before signing the data, which is part of  standard RSASSA-PKCS1-v1_5 (https://datatracker.ietf.org/doc/html/rfc3447#section-8.2). 
**(!) Attention: this change will break existing signatures**
Fixes #
```noteworthy user
- pass in hash function in rsa.Sign() and rsa.Verify() calls instead of passing in 0. this will apply EMSA-PKCS1-v1_5 encoding (https://datatracker.ietf.org/doc/html/rfc3447#section-9.2) before signing the data, which is part …
```

configurable hash functions
