bindings-python/gci/componentmodel.py, component-descriptor-v2-schema.yaml, language-independent/test-resources/component_descriptor_v2.yaml
@schrodit : I suppose, the go-bindings also need to be adjusted
=> add (optional) labels, and componentref-names

bindings-go/apis/v2/componentdescriptor.go, bindings-go/apis/v2/validation/validation.go, bindings-go/apis/v2/validation/validation_test.go
Re-add overwritten features
```improvement operator
NONE
```
=> Fix overwritten changes

bindings-go/apis/v2/componentdescriptor.go, bindings-go/codec/codec.go, bindings-go/codec/codec_suite_test.go
Fixes #
```improvement operator
```
=> Fix component encoding

bindings-python/gci/componentmodel.py
- define an identity-type for each of cref, resource, and source
- normalise id-attrs by sorting them alphabetically
- special-case for v2: implicitly add `version` to avoid collisions
=> calculate identity

bindings-go/apis/v2/accesstypes.go, bindings-go/apis/v2/cdutils/utils.go, bindings-go/apis/v2/componentdescriptor.go, bindings-go/apis/v2/helper.go, bindings-go/apis/v2/v2_suite_test.go, bindings-go/apis/v2/validation/validation.go, bindings-go/apis/v2/validation/validation_test.go, bindings-go/ctf/componentarchive.go, bindings-go/ctf/ctf.go, bindings-go/oci/constants.go, bindings-go/oci/manifest.go, bindings-go/oci/resolve.go
Expose some functions that are used in the component cli.
```improvement operator
NONE
```
=> expose functions that are used in the component-cli

bindings-python/gci/componentmodel.py, doc/format.rst, language-independent/component-descriptor-v2-schema.yaml, language-independent/test-resources/component_descriptor_v2.yaml
Adds additional valdation for component-names, logical names and versions.
=> Refine CDv2 schema

bindings-python/gci/componentmodel.py
Fixes #
```improvement operator
NONE
```
=> add local oci and filesystem blob definitions to the python binding

bindings-python/gci/componentmodel.py
Fixes #
```improvement operator
```
=> Added: missing helm resource type

bindings-python/gci/componentmodel.py, bindings-python/tests/gci/componentmodel_test.py
Fixes #
```improvement operator
```
=> deserialize unkown access into ResourceAccess

bindings-python/gci/componentmodel.py, bindings-python/tests/gci/componentmodel_test.py
adds method for setting/overwriting labels
Fixes #
```improvement operator
```
=> adds set_label method

language-independent/component-descriptor-v2-schema.yaml
This PR updates the json schema to the latest version.
Fixes #
```improvement operator
NONE
```
=> Update json schema version

doc/oci.rst
None
```improvement operator
NONE
```
=> Fix typo in oci.rst

bindings-go/apis/v2/componentdescriptor.go, bindings-go/apis/v2/signatures/rsa.go, bindings-go/apis/v2/signatures/rsa_test.go, bindings-python/gci/componentmodel.py, language-independent/component-descriptor-v2-schema.yaml
- adds media type field to a signature
- adds support for signatures in pem format in rsa verifier
- fix unit tests
Fixes #
```improvement operator
- adds media type field to a signature
- adds support for signatures in pem format in rsa verifier
```
=> enhance signatures

doc/proposal/00-overview.md, doc/proposal/02-component-descriptor.md, doc/proposal/04-local-blobs.md, doc/proposal/app01-external-references.md, doc/proposal/component-descriptor-v2-schema.yaml, doc/proposal/in-progress/05-component-repository-oci.md, doc/proposal/in-progress/06-local-references.md, doc/proposal/in-progress/06-tranport-format.md, doc/proposal/leftovers.md
This PR mainly switches to a table based description of fields.
Fixes #
```improvement operator
NONE
```
=> Rework CD section

doc/proposal/01-introduction.md, doc/proposal/04-local-blobs.md, doc/proposal/leftovers.md
Feedback of OCM docu integrated.
Fixes #
```improvement operator
NONE
```
=> Feedback for OCM Docu

doc/proposal/leftovers.md
OCM Docu feedback
Fixes #
```improvement operator
NONE
```
=> OCM Docu feedback

bindings-go/apis/v2/signatures/sign.go
Improves internal verification handling
Fixes #
```improvement user
signature verify: improves internal verification handling coding
```
=> improved signature verification

bindings-go/apis/v2/resources.go, bindings-python/gci/componentmodel.py
adds cosign signature resource type
Fixes #
```improvement user
- adds cosign signature resource type
```
=> adds cosign signature resource type

doc/proposal/02-component-descriptor.md
This PR includes the inclusion of the version to the identity of references.
Fixes #
```improvement operator
NONE
```
=> include version in identity of reference

doc/proposal/00-overview.md, doc/proposal/01-introduction.md, doc/proposal/02-component-descriptor.md, doc/proposal/03-component-repository.md, doc/proposal/04-local-blobs.md, doc/proposal/app01-external-references.md, doc/proposal/leftovers.md
Improve OCM spec. with Uwe's feedback.
Fixes #
```improvement operator
NONE
```
=> integrate feedback from uwe

doc/proposal/in-progress/07-signing.md
Adds the signing spec in the new spec repo.
Fixes #
```improvement operator
```
=> Signing Spec

bindings-python/gci/componentmodel.py
add exclude from signature digest to python binding
Fixes #
```improvement operator
```
=> add exclude from signature digest to python binding

bindings-go/oci/resolve.go
Fixes #
```improvement operator
```
=> Add length check for url.Parse

bindings-go/apis/v2/componentdescriptor.go, bindings-go/go.mod, bindings-go/go.sum
Fixes #
```noteworthy developer
go-binding: change type of creationTime to string
```
=> Change type of creationTime to string
